//const API_URL = "http://localhost/bsi_nuworld/public/api/";
//export const BACKEND_STORAGE_URL = "http://localhost/bsi_nuworld/public/storage/app/public/users/";
// const API_URL = "https://dpmetro.in/api/";
export const BACKEND_STORAGE_URL = "https://dpmetro.in/storage/app/public/users/";
const API_URL = "http://192.168.1.7/nuworld/public/api/";
//export const BACKEND_STORAGE_URL = "https://dpmetro.in/storage/app/public/users/";
//const API_URL = "https://salesadmin.nuworld.co.in/api/";
//export const BACKEND_STORAGE_URL = "https://salesadmin.nuworld.co.in/storage/app/public/users/";


export const API_AUTHORIZATION_CODE = "BSI_AUTH_NEXTDYNAMIC_NAVTEJ_JANMASTMI";
export const otp_request = API_URL + "otp_request";
export const agreement_acceptance = API_URL + "agreement_acceptance";
export const login_user = API_URL + "login_user";
export const underSponsor = API_URL + "underSponsor";
export const assets = API_URL + "assets";
export const investorsListApi = API_URL + "investorsList";
export const investorsListTeam = API_URL + "investorsListTeam";
export const add_investor = API_URL + "add_investor";
export const single_investor = API_URL + "single_investor";
export const paymentList = API_URL + "paymentList";
export const addPayment = API_URL + "addPayment";
export const profile = API_URL + "profile";
export const logout = API_URL + "logout";
export const investorDashboard = API_URL + "investorDashboard";
export const single_asset = API_URL + "single_asset";
export const get_down_data = API_URL + "get_down_data";
export const downtree = API_URL + "downtree";
export const chatAdd = API_URL + "chatAdd";
export const chatList = API_URL + "chatList";
export const single_chat = API_URL + "single_chat";
export const check_first_payment = API_URL + "check_first_payment";
export const payment_gateway = API_URL + "paymentgateway";
export const verify_pan_aadhar = API_URL + "verify";
export const fetch_kyc_status = API_URL + "fetchkycstatus";
export const otp_request_email = API_URL + "otp_request_email";
export const otp_request_email_verify = API_URL + "otp_request_email_verify";
export const user_token_expire = API_URL + "verify_login"