export const commonMessage = {
    common:{
        "sure":"Are you sure",
        "success":"Success",
        "failed":"Failed",
        "aborted":"Action Aborted",
        "resetForm":"Reset Form",
        "validationError":"Validation Error",
        "uploadSuccess":"Files has been uploaded successfully.",
        "uploadFailed":"Files failed to upload.",
        "validFileError":"Please select valid file.",
        "fileSizeError":"Please upload a file smaller than 10 MB",
        "addFile":"File successfully Added.",
        "confirmResetForm":"Are you sure to reset the form",
        "confirmFormResetSuccess":"Form Reset Successfully.",
        "selectFileMsg":"Please select file.",
        "confirmFormResetFailed":"Form Reset Failed.",
        "confirmChangePass":"Are you sure to change the password.",
        "confirmResetPass":"Are you sure to reset the password.",
        "changePassSuccess":"Password changes successfully.",
        "changePassFailed":"Password failed to change.",
        "welcomeMsg":"Welcome To Cypher.",
        "registerSuccess":"Thank you! for register.",
        "emailValidation":"Kindly check the email you have entered.",
        "employeeAddSuccess":"Employee has been added successfully.",
        "orderPlace":"Thank you! your order has been places successfully.",
        "orderFinanceMsg":"New order found! kindly process it accordingly",
        "orderEdit":"Order has been updated successfully.",
        "orderEditFailed":"Order failed to updated.",
        "orderCancelSuccess":"Order has been cancel successfully.",
        "orderCancelFailed":"Order failed to cancel.",
        "contractCreateSuccess":"Contract has been created successfully",
        "contractCreateFailed":"Contract failed to create",
        "acceptOrder":"You have accept the order.",
        "acceptContract":"You have accept the contract",
        "shipmentSuccess":"Order has been shipped successfully.",
        "shipmentFailed":"Order failed to shipped.",
        "shipmentAccept":"Order has been accepted.",
        "shipmentDelivery":"Order has been delivered to the destination.",
        "invalidForm":"Invalid Form",
        "invalidFormMsg":"Invalid form kindly check the input details",
        "invalidFile":'Invalid File'
    },
    commonButtonLabel:{
        "Submit":"Submit",
        "Save":"Save",
        "Cancel":"Cancel",
        "Upload":"Upload",
        "Add":"Add",
        "Reset":"Reset",
        "Edit":"Edit",
        "Update":"Update",
        "Open":"Open",
        "Close":"Close",
    },
    headingsLabel:{
        "orderList":"Order List",
        "contractList":"Contract List",
        "tradeList":"Trade List",
        "employeeList":"Employee List",
        "verification":"Verification document",
        "categoryMng":"Category Management",
        "supplierMng":"Supplier Management",
        "catalogueMng":"Catalogue Management",
        "orderPlace":"Place Order",
        "contractPlace":"Place Contract",
        "tradePlace":"Place Trade",
    }
}